CREATE TABLE [dbo].[Movie_Person]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	PersonId INT NOT NULL,
	MovieId INT NOT NULL,
	Role VARCHAR(100) NOT NULL

	CONSTRAINT FK_Movie FOREIGN KEY (MovieId) REFERENCES Movie(Id),
	CONSTRAINT FK_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
)
