CREATE TABLE [dbo].[UserAccount]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Email] VARCHAR(100) NOT NULL UNIQUE,
	[Nickname] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(MAX) NOT NULL,
	[IsAdmin] BIT DEFAULT 0
)
